language: java
jdk:
- oraclejdk8
os:
- linux
cache:
  bundler: true
  apt: true
  directories:
  - $HOME/.m2
  - $HOME/.cache/pip
script:
  - mvn -DskipTests=true package -Dmaven.javadoc.skip=true -B -V
deploy:
 - ls
notifications:
  - lizhao@mokylin.com
